[KTB-13]: 블로그 게시글 디테일 개선
ktb6/ktb6-teamblog pull request #8
Opened 2024-07-08 02:19 UTC by Youthhing

KTB-13 블로그 게시글 디테일 개선

### 🎯 목적
- 블로그 게시글 UI의 디테일을 개선한다.

### ✅ 작업 내용
- 게시글 가운데 정렬 기능 추가
- 저자 정보 및 포지션 업데이트

### 🗣 ️리뷰 요구 사항
- 병합 후 충돌 가능성 확인 여부
- 추가적인 개선 아이디어

2024-07-08 08:26 UTC, Danny-Jo requested changes
develop에 새 pr이 머지되어서 KTB-1이 rebase하다보니 여기서도 conflict가 나네요.
KTB-1를 리베이스해서 conflict 해결하고 다시 request 주시면 감사하겠습니다.

2024-07-08 09:44 UTC, Youthhing commented
> develop에 새 pr이 머지되어서 KTB-1이 rebase하다보니 여기서도 conflict가 나네요. KTB-1를 리베이스해서 conflict 해결하고 다시 request 주시면 감사하겠습니다.

@Danny-Jo KTB-1을 기준으로 rebase후 PR을 올리면 될까요?

2024-07-08 12:39 UTC, Danny-Jo commented
네 KTB-1를 pull 하신 후에 이 브랜치에서 KTB-1를 rebase하면 됩니다

2024-07-09 05:45 UTC, Danny-Jo requested changes
엇 확인해보니 아까 all current change로 merge하는게 정상적으로 되지 않은 것 같네요. 몇몇 파일이 conflict 난 상태로 있습니다. 확인해보시고 본인이 작업한 부분은 incoming으로, 남들이 작업한 부분은 current로 accept한 다음 다시 push 한 번 해주시면 될 것 같습니다.

2024-07-09 06:45 UTC, Youthhing commented
> 엇 확인해보니 아까 all current change로 merge하는게 정상적으로 되지 않은 것 같네요. 몇몇 파일이 conflict 난 상태로 있습니다. 확인해보시고 본인이 작업한 부분은 incoming으로, 남들이 작업한 부분은 current로 accept한 다음 다시 push 한 번 해주시면 될 것 같습니다.

Conflict solve 후 push 했습니다!

2024-07-09 07:06 UTC, Danny-Jo approved these changes
확인 완료했습니다 잘되네요! 머지해도 좋을 것 같습니다

2024-07-09 08:16 UTC, merged